Initialize Sentiment Analyzer

In [1]:
import nltk
import warnings
warnings.filterwarnings('ignore')
from nltk.sentiment.vader import SentimentIntensityAnalyzer
nltk.downloader.download('vader_lexicon')

sia = SentimentIntensityAnalyzer()

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /Users/shubham/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

Updating Vader Lexicon with External Lexicon

In [2]:
# import csv
import pandas as pd

filtering positive and negative words from L&M dictionary into seperate csv.

In [3]:
lexicons = pd.read_csv('./datasets/Loughran-McDonald_MasterDictionary_1993-2021.csv')

In [4]:
len(lexicons)

86531

In [5]:
len(lexicons[lexicons['Negative'] != 0])

2355

In [6]:
positive_words = lexicons[lexicons['Positive'] != 0]

In [8]:
#positive_words.to_csv('./datasets/positive_words.csv')

In [9]:
negative_words = lexicons[lexicons['Negative'] != 0]

In [10]:
#negative_words.to_csv('./datasets/negative_words.csv')

working on stock market lexicon dictionary from https://github.com/nunomroliveira/stock_market_lexicon

In [12]:
stock_lex = pd.read_csv('./datasets/stock_lexicons.csv')

In [13]:
stock_lex['sentiment'] = (stock_lex['Aff_Score'] + stock_lex['Neg_Score'])/2

creating a dictionary w/ item as key and sentiment score as value

In [14]:
stock_lex = dict(zip(stock_lex.Item, stock_lex.sentiment))

dictionary comprehension to remove any key:value pair where key's length > 1

In [15]:
stock_lex = {k:v for k,v in stock_lex.items() if len(k.split(' '))==1}

standardizing the sentiment score of lexicon dictionary between (-4,4)

In [16]:
stock_lex_scaled = {}

In [17]:
for k, v in stock_lex.items():
    if v > 0:
        stock_lex_scaled[k] = v / max(stock_lex.values()) * 4
    else:
        stock_lex_scaled[k] = v / min(stock_lex.values()) * -4

In [18]:
positive = []

In [19]:
for word in positive_words['Word'].to_list():
    item = word.strip().split(' ')
    if len(item) > 1:
        positive.extend(item)
    else:
        positive.append(item[0])

In [20]:
negative = []

In [21]:
for word in negative_words['Word'].to_list():
    item = word.strip().split(' ')
    if len(item) > 1:
        negative.extend(item)
    else:
        negative.append(item[0])

In [22]:
final_lex = {}

In [23]:
final_lex.update(sia.lexicon)
# using dict comprehension creating a dictionary from list and assigning each word value 2/-2
final_lex.update({word:2.0 for word in positive})
final_lex.update({word:-2.0 for word in negative})
final_lex.update(stock_lex_scaled)

In [44]:
final_lex_df = pd.DataFrame(list(final_lex.items()), columns=['word', 'sentiment_score'])

In [45]:
#final_lex_df.to_csv('./datasets/lexicon_dictionary.csv')

updating the original SentimentIntensityANalyzer lexicon dictionary

In [28]:
sia.lexicon = final_lex

reading nifty 500 articles

In [29]:
nifty_articles = pd.read_csv('./datasets/NIFTY_500_Articles.csv')

In [30]:
art_scores = pd.DataFrame(nifty_articles['Headline'].apply(sia.polarity_scores).to_list())

In [32]:
art_scores_df = pd.merge(nifty_articles, art_scores,
                         left_index=True, right_index=True)

In [41]:
(art_scores_df.iloc[:,1:])[art_scores_df['Ticker'] == 'ADANIENT']

,Ticker,Headline,Date,Time,neg_x,neu_x,pos_x,compound_x,neg_y,neu_y,pos_y,compound_y
483,ADANIENT,Adani Enterprises incorporates Wholly Owned Su...,2023/04/12,09:18,0.000,1.000,0.000,0.0000,0.000,1.000,0.000,0.0000
484,ADANIENT,Adani Enterprises informs about clarification ...,2023/03/29,09:57,0.000,1.000,0.000,0.0000,0.000,0.327,0.673,0.2886
485,ADANIENT,Adani Enterprises’ arm completes acquisition o...,2023/03/28,09:38,0.000,1.000,0.000,0.0000,0.146,0.416,0.439,0.4982
486,ADANIENT,"BSE, NSE remove 3 Adani group companies from s...",2023/03/17,15:30,0.000,1.000,0.000,0.0000,0.209,0.502,0.289,0.2012
487,ADANIENT,Adani Group repays loans of $2.65 billion to c...,2023/03/13,12:12,0.000,1.000,0.000,0.0000,0.366,0.495,0.139,0.0640
488,ADANIENT,"Adani group repays Rs 7,374 crore share-backed...",2023/03/09,11:19,0.000,1.000,0.000,0.0000,0.000,0.686,0.314,0.1883
489,ADANIENT,Adani portfolio companies sell stakes worth Rs...,2023/03/03,14:52,0.000,0.853,0.147,0.2263,0.078,0.616,0.306,0.2402
490,ADANIENT,Adani Enterprises informs about disclosure,2023/03/03,12:54,0.000,1.000,0.000,0.0000,0.000,0.578,0.422,0.0497
491,ADANIENT,Adani Enterprises’ arm emerges as preferred bi...,2023/03/03,12:11,0.225,0.775,0.000,-0.4404,0.000,0.363,0.637,0.5802
492,ADANIENT,Adani Enterprises’ arm emerges as preferred bi...,2023/03/01,11:58,0.195,0.805,0.000,-0.4404,0.069,0.379,0.553,0.5677
493,ADANIENT,Adani Enterprises informs about web link of tr...,2023/02/18,12:18,0.000,1.000,0.000,0.0000,0.151,0.223,0.625,0.6568
494,ADANIENT,Adani Enterprises reports many fold jump in Q3...,2023/02/14,16:22,0.000,0.775,0.225,0.4404,0.158,0.376,0.466,0.4764
495,ADANIENT,Adani Enterprises - Quaterly Results,2023/02/14,13:55,0.000,1.000,0.000,0.0000,0.000,1.000,0.000,0.0000
496,ADANIENT,Adani Enterprises - Quaterly Results,2023/02/14,13:55,0.000,1.000,0.000,0.0000,0.000,1.000,0.000,0.0000
497,ADANIENT,Adani Enterprises - Quaterly Results,2023/02/14,13:55,0.000,1.000,0.000,0.0000,0.000,1.000,0.000,0.0000
498,ADANIENT,Adani Enterprises informs about media release,2023/01/28,15:08,0.000,1.000,0.000,0.0000,0.000,0.423,0.577,0.2698
499,ADANIENT,"Adani Enterprises raises Rs 5,985 crore from a...",2023/01/27,11:28,0.000,1.000,0.000,0.0000,0.166,0.554,0.280,0.3914
500,ADANIENT,Adani Enterprises submits media statement,2023/01/25,16:33,0.000,1.000,0.000,0.0000,0.000,0.512,0.488,0.2178
501,ADANIENT,Adani group planning to spin off businesses of...,2023/01/23,11:11,0.000,1.000,0.000,0.0000,0.276,0.453,0.272,0.2357
502,ADANIENT,Adani Enterprises’ arm incorporates JV Company,2023/01/21,17:16,0.000,1.000,0.000,0.0000,0.000,0.645,0.355,0.0532
503,ADANIENT,Adani Enterprises planning to enter water segment,2023/01/20,11:06,0.000,1.000,0.000,0.0000,0.543,0.249,0.208,0.0794
504,ADANIENT,"Adani Enterprises files for Rs 20,000 crore FPO",2023/01/19,11:27,0.000,1.000,0.000,0.0000,0.000,0.872,0.128,0.0081
505,ADANIENT,Adani Enterprises inks pact with Ashok Leyland...,2023/01/18,10:51,0.000,1.000,0.000,0.0000,0.131,0.487,0.381,0.4766
506,ADANIENT,"Adani Group planning to invest Rs 60,000 crore...",2023/01/12,11:30,0.000,1.000,0.000,0.0000,0.277,0.447,0.277,0.2512
507,ADANIENT,Adani to pay additional amount for NDTV shares...,2023/01/04,16:31,0.096,0.753,0.151,0.2023,0.194,0.192,0.614,0.5547
508,ADANIENT,Adani Enterprises informs about update on open...,2023/01/03,14:41,0.000,1.000,0.000,0.0000,0.240,0.333,0.427,0.1752
509,ADANIENT,Adani Enterprises informs about acquisition,2022/12/30,09:41,0.000,1.000,0.000,0.0000,0.000,0.496,0.504,0.2608
510,ADANIENT,Adani Enterprises’ arm acquires 27.26% stake i...,2022/12/30,09:30,0.000,1.000,0.000,0.0000,0.122,0.559,0.319,0.1942
511,ADANIENT,Adani Enterprises informs about updates on acq...,2022/12/28,14:24,0.000,1.000,0.000,0.0000,0.000,0.492,0.508,0.2803
512,ADANIENT,Adani Enterprises acquires 100% stake in SIBIA,2022/12/28,12:11,0.000,1.000,0.000,0.0000,0.138,0.632,0.230,0.1850
513,ADANIENT,Adani Group’s arm introduces India’s first lar...,2022/12/21,18:14,0.000,1.000,0.000,0.0000,0.093,0.722,0.185,0.0066
514,ADANIENT,Adani Enterprises informs about incorporation ...,2022/12/17,15:22,0.000,1.000,0.000,0.0000,0.111,0.763,0.126,0.0370
515,ADANIENT,Adani Enterprises’ JV incorporates wholly owne...,2022/12/17,15:19,0.000,1.000,0.000,0.0000,0.000,1.000,0.000,0.0000
516,ADANIENT,Adani Enterprises acquires entire stake in All...,2022/12/09,10:14,0.000,1.000,0.000,0.0000,0.102,0.468,0.431,0.3643
517,ADANIENT,Adani Enterprises gets nod to raise funds up t...,2022/11/28,11:20,0.000,1.000,0.000,0.0000,0.152,0.603,0.245,0.3029
518,ADANIENT,Adani Enterprises informs about analyst meet,2022/11/19,15:01,0.000,1.000,0.000,0.0000,0.175,0.454,0.370,0.0742
519,ADANIENT,Adani Enterprises informs about clarification ...,2022/11/17,16:38,0.000,1.000,0.000,0.0000,0.084,0.309,0.607,0.4161
520,ADANIENT,Adani group gets SEBI’s nod to buy additional ...,2022/11/15,11:59,0.000,1.000,0.000,0.0000,0.146,0.417,0.437,0.4896
521,ADANIENT,Adani Enterprises’ JV signs MoU with Adani Power,2022/11/10,17:41,0.000,1.000,0.000,0.0000,0.000,0.571,0.429,0.5436
522,ADANIENT,Adani Enterprises’ JV opens Flagship Data Cent...,2022/11/04,15:27,0.000,0.865,0.135,0.1027,0.093,0.596,0.311,0.3752
523,ADANIENT,Adani Enterprises reports 2- fold jump in Q2 c...,2022/11/04,11:59,0.000,0.775,0.225,0.4404,0.082,0.452,0.467,0.4785
524,ADANIENT,Adani Enterprises - Quaterly Results,2022/11/03,18:19,0.000,1.000,0.000,0.0000,0.000,1.000,0.000,0.0000
525,ADANIENT,Adani Enterprises - Quaterly Results,2022/11/03,18:19,0.000,1.000,0.000,0.0000,0.000,1.000,0.000,0.0000
526,ADANIENT,Adani Enterprises’ arm inks definitive agreeme...,2022/10/19,10:16,0.000,0.811,0.189,0.2732,0.189,0.412,0.399,0.3705
527,ADANIENT,Adani Enterprises signs binding term sheet to ...,2022/10/17,10:22,0.000,1.000,0.000,0.0000,0.351,0.381,0.268,0.2302
528,ADANIENT,Adani Enterprises’ unit gets unified licence f...,2022/10/12,14:32,0.000,0.755,0.245,0.3818,0.087,0.419,0.494,0.5929
529,ADANIENT,Adani Enterprises informs about compliance cer...,2022/10/07,17:10,0.000,1.000,0.000,0.0000,0.000,0.605,0.395,0.1553
530,ADANIENT,Adani Enterprises incorporates two wholly owne...,2022/10/06,11:23,0.000,1.000,0.000,0.0000,0.000,1.000,0.000,0.0000
531,ADANIENT,Adani Enterprises’ arms get financial closure ...,2022/09/30,14:15,0.000,1.000,0.000,0.0000,0.000,0.481,0.519,0.1192
532,ADANIENT,Adani Enterprises raises Rs 100 crore via MLD,2022/09/28,10:30,0.000,1.000,0.000,0.0000,0.130,0.870,0.000,-0.0120

In [46]:
lex_fin = pd.read_csv('./datasets/lexicon_dictionary.csv')

In [47]:
lex_fin

       Unnamed: 0           word  sentiment_score
0               0             $:        -1.500000
1               1             %)        -0.400000
2               2            %-)        -1.500000
3               3            &-:        -0.400000
4               4             &:        -0.700000
...           ...            ...              ...
15191       15191           zoom        -0.373068
15192       15192  zortrades.com         1.718507
15193       15193            zte         4.000000
15194       15194           zuck        -0.121264
15195       15195     zuckerberg        -0.156683

[15196 rows x 3 columns]

In [50]:
lex_dict = dict(zip(lex_fin.word, lex_fin.sentiment_score))